version: '3'
services:
  app:
    build: .
    container_name: disaster-api-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis:alpine
    container_name: disaster-api-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: