version: '3'
services:
  app:
    build: .
    container_name: disaster-api-app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
  redis:
    image: redis:alpine
    container_name: disaster-api-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: